Edoc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler404
from src.accounts import views
from src.document import views
# handler404 = views.custom_404_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("src.accounts.urls")),
    path('document/', include("src.document.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/document/urls.py
from django.urls import path
from . import views
app_name = 'document'
urlpatterns = [
    path('', views.add_document, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('',views.sign_up , name='signup'),
    # path('login/',views.user_login , name='login'),
    # path('logout/',views.user_logout, name='logout'),
    path('document/<int:document_id>/', views.document_version, name='document_version'),
    path('document/update/<int:document_id>/', views.update_doc, name='update_doc'),
    path('document/delete/<int:document_id>/', views.delete_document, name='delete_document'),
    path('document/<int:document_id>/share/', views.share_document, name='share'),
    path('document/share/', views.shared_documents_list, name='shared'),
    path('document/download/<path:file_path>/', views.download_document, name='download_file'),
    path('document/share/permission/<int:document_id>/', views.permission, name='permission'),
    path('serve_document/<int:document_version_id>/', views.serve_document, name='serve_document'),

]

src/document/models.py
from django.db import models
import datetime
from django.utils import timezone
from src.accounts.models import AdminUser
from django.core.files.storage import FileSystemStorage
from django.conf import settings 
# Create your models here.

class DocumentDetails(models.Model):
    created_by = models.ForeignKey(AdminUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    description = models.TextField(max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    def create_doc(self):
        return self.created_date >= timezone.now() - datetime.timedelta(days=1) 
    
class DocumentVersion(models.Model):
    doc = models.ForeignKey(DocumentDetails, on_delete=models.CASCADE)
    file = models.FileField(upload_to='E_document/',storage=FileSystemStorage(location=settings.MEDIA_ROOT))
    version = models.FloatField(default=1.0, null=True,blank=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.doc)
    
class DocumentShared(models.Model):
    document = models.ForeignKey(DocumentDetails, on_delete=models.CASCADE)
    receiver = models.ForeignKey(AdminUser, related_name='received_documents', on_delete=models.CASCADE)
    shared_user = models.ForeignKey(AdminUser,related_name='shared_documents',on_delete=models.CASCADE)
    shared_doc_view = models.BooleanField(default=False)
    shared_doc_update = models.BooleanField(default=False)
    shared_doc_download = models.BooleanField(default=False)
    def __str__(self):
        return f'Shared Document: {self.document.name} from {self.shared_user} to {self.receiver}'

class DocumentTracking(models.Model):
    action = models.CharField(choices=[('Add New Document','Add New Document'),('Add Version','Add Version'),('Document Shared','Document Shared'),('View','View'),('Edit','Edit'),('Download','Download'),('Delete','Delete')],max_length=200)
    created_date =  models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(AdminUser,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.user} performed {self.action} on {self.created_date}'
        

src/document/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import DocumentShared

class DocumentShareForm(forms.ModelForm):
    shared_doc_view = forms.BooleanField(label="View:",required=False)
    shared_doc_update = forms.BooleanField(label="Update:",required=False)
    shared_doc_download = forms.BooleanField(label="Download:",required=False)
    class Meta:
        model = DocumentShared
        fields = ['shared_user', 'shared_doc_view', 'shared_doc_update', 'shared_doc_download']

# class DocumentSharedForm(forms.ModelForm):
#     shared_doc_view = forms.BooleanField(label="View       :",required=False)
#     shared_doc_update = forms.BooleanField(label="Update       :",required=False)
#     shared_doc_download = forms.BooleanField(label="Download       :",required=False)

#     class Meta:
#         model = DocumentShared
#         fields = [
#             'shared_user',
#             'document',
#             'receiver',
#             'shared_doc_view',
#             'shared_doc_update',
#             'shared_doc_download',
#         ]
#         widgets = {
#             'shared_user': forms.Select(attrs={'class': 'form-control'}),
#             'shared_doc_view': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
#             'shared_doc_update': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
#             'shared_doc_download': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
#         }

src/document/views.py
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseNotFound,HttpResponse
from .forms import DocumentShareForm 
from django.template import loader
from src.accounts.models import AdminUser
from django.contrib.auth.forms import AuthenticationForm
from .models import DocumentDetails,DocumentVersion,DocumentShared,DocumentTracking
from django.contrib import messages
import os
from django.conf import settings 
from django.http import FileResponse, HttpResponse
from django.shortcuts import get_object_or_404
import mimetypes


# Create your views here.
# def sign_up(request):
#     if request.method == "POST":
#         username= request.POST.get('username')
#         first_name= request.POST.get('first_name')
#         last_name= request.POST.get('last_name')
#         email= request.POST.get('email')
#         password1= request.POST.get('password1')
#         password2= request.POST.get('password2')
#         if password1 == password2:
#             if AdminUser.objects.filter(username=username).exists():
#                 messages.info(request, 'Username is already taken')
#                 return redirect('document:signup')
#             elif AdminUser.objects.filter(email=email).exists():
#                 messages.info(request, 'Email is already taken')
#                 return redirect('document:signup')
#             else:
#                 userdetails = AdminUser.objects.create_user(username=username, password=password1, 
#                                         email=email, first_name=first_name, last_name=last_name)
#                 userdetails.save()
#                 print(userdetails)
#                 return redirect('document:login')
#         else:
#             messages.info(request, 'Both passwords are not matching')
#             return redirect('document:signup')
#     else:
#         print("last else")
#         return render (request,'document/signup.html')

# def user_login(request):
#     if request.method == "POST":
#         form = AuthenticationForm(request=request, data=request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             user = authenticate(username = username , password = password)
#             if user is not None:
#                 login(request,user)
#                 return redirect('document:dashboard')
#     return render(request,'document/login.html')
   
# def user_logout(request):
#     logout(request)
#     return redirect('document:login')

def dashboard(requrst):
    user = AdminUser.objects.all()
    if requrst.user != user:  
        return render(requrst,'document/dashboard.html')
    else:
        return redirect('document:home')

@login_required
def add_document(request):
        if request.method == 'POST':
            name= request.POST.get('name')
            description= request.POST.get('description')
            docdetails = DocumentDetails(name = name,
                                    description = description,
                                    created_by=request.user
                                    )
            docdetails.save()
        document= DocumentDetails.objects.filter(created_by=request.user)
        if request.method == 'GET':
            query = request.GET.get('search')
            if query!= None:
                document = DocumentDetails.objects.filter(name__icontains=query)
        template = loader.get_template("document/home.html")
        return render(request,'document/home.html',{'document':document})

@login_required    
def update_doc(request,document_id):
        doc = DocumentDetails.objects.get(pk=document_id)
        if request.method == 'POST':
            doc.name = request.POST.get('name')
            doc.description = request.POST.get('description')
            doc.save()
            return redirect('document:home')
        else:
            DocumentTracking.objects.create(action='Edit', user=request.user)
            return render(request, 'document/edit.html', {"doc": doc})
        
def delete_document(request, document_id):
    document = DocumentDetails.objects.get(id=document_id)
    if request.method == 'POST':
        document.delete()
        DocumentTracking.objects.create(action='Delete', user=request.user)
        return redirect('document:home')
    else:
        return render(request, 'document/delete.html')  
   
@login_required
def document_version(request, document_id):
        doc = DocumentDetails.objects.get(pk=document_id)
        versions = DocumentVersion.objects.filter(doc=doc)
        if request.method == 'POST':
            file = request.FILES.get('file')
            latest_version = 0
            try:
                latest_version = DocumentVersion.objects.filter(doc = doc).order_by("-version").first().version
            except:
                print(" you upload first file in this document")
            DocumentVersion.objects.create(doc = doc,file = file,
                                    version = latest_version +1.0)
        DocumentTracking.objects.create(action='View', user=request.user)     
        return render(request, 'document/view.html', {"doc": doc, "versions": versions})
    
@login_required
def serve_document(request, document_version_id):
    version = get_object_or_404(DocumentVersion, pk=document_version_id)
    file = version.file

    # Determine the file's content type
    content_type, _ = mimetypes.guess_type(file.name)

    response = FileResponse(file, content_type=content_type)
    response['Content-Disposition'] = f'inline; filename="{os.path.basename(file.name)}'

    return response


@login_required
def download_document(request,file_path):
    DocumentTracking.objects.create(action='Download', user=request.user)     
    path = os.path.join(settings.MEDIA_ROOT, file_path)   
    if os.path.exists(path):
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(),content_type ="application/file")
            response['Content-Disposition'] = 'inline; filename='+os.path.basename(path)
            return response
    else:
        return HttpResponseNotFound('File not found.')

    
@login_required
def share_document(request, document_id):
    document = DocumentDetails.objects.get(id=document_id)
    users = AdminUser.objects.all()
    if request.method == 'POST':
        form = DocumentShareForm(request.POST)
        if form.is_valid():
            shared_user = form.cleaned_data['shared_user']
            shared_doc_view = form.cleaned_data.get('shared_doc_view', False)
            shared_doc_update = form.cleaned_data.get('shared_doc_update', False)
            shared_doc_download = form.cleaned_data.get('shared_doc_download', False)
            shared_document = DocumentShared(
                document=document,
                receiver=request.user,
                shared_user=shared_user,
                shared_doc_view=shared_doc_view,
                shared_doc_update=shared_doc_update,
                shared_doc_download=shared_doc_download)
            shared_document.save()
            return redirect('document:home') 
    else:
        form = DocumentShareForm()
    
    return render(request, 'document/share.html', {'form': form, 'document': document, 'users':users})

@login_required
def shared_documents_list(request):
    shared_documents = DocumentShared.objects.filter(shared_user=request.user)
    print("--------------------->",shared_documents)
    if request.method == 'POST':
            query = request.POST.get('search')
            if query!= None:
                shared_documents = DocumentShared.objects.filter(document__name__icontains = query)
    template = loader.get_template("document/receive.html")
    return render(request, 'document/receive.html', {'shared_document': shared_documents})

@login_required
def permission(request, document_id):
    if request.method == 'POST':
        action = request.POST.get('action')
        document = DocumentDetails.objects.get(id=document_id)
        shared_documents = DocumentShared.objects.filter(document=document, shared_user=request.user)
        for shared_document in shared_documents:
            if action == 'view' and shared_document.shared_doc_view:
                return redirect('document:document_version', document_id=document_id)            
            elif action == 'update' and shared_document.shared_doc_update:
                return redirect('document:update_doc', document_id=document_id)               
            elif action == 'download' and shared_document.shared_doc_download:
                return redirect('document:document_version', document_id=document_id)
            else:
                return redirect('document:shared')
    return render(request, 'document/receive.html')

templates/document/edit.html
{% extends 'document/dashboard.html' %}
{% block title %} Edit Document {% endblock%}
{% block content %}
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Document</h1>
    </div>
 <!-- Basic Card Example -->
 <div class="row">
 <div class="col-lg-9">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-secondary">Edit Existing Document</h6>
        </div>
        <div class="card-body">
            <!-- === -->
            <form  method="POST" action="{% url 'document:update_doc' doc.id %}">
                {% csrf_token %}
                <!-- <label for="name">Name &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; :</label> -->
                <input type="text" class="form-control bg-gray-200 border-0 small" name="name" value="{{ doc.name }}"
                    aria-label="Search" aria-describedby="basic-addon2"><br>
                <!-- <label for="description">Description &nbsp;:</label> -->
                <textarea class="form-control bg-gray-200 border-0 small truncate-text" name="description" value="{{doc.description }}" 
                    aria-label="Search" aria-describedby="basic-addon2"></textarea><br>
                    <button class="btn btn-secondary btn-icon-split text " type="submit">Save Change </button>
                    
              </form>
        </div>
    </div>
</div>
<div class="col-lg-3">
    <div class="card shadow mb-2">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-secondary">Add New Version</h6>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'document:document_version' doc.id %}" enctype="multipart/form-data"> 
                {% csrf_token %}
                  File : <input type="FILE" name="file" ><br><br>
                  <button class="btn btn-secondary btn-icon-split text " type="submit">Add File </button>
              </form>
        </div>
    </div>
</div>
</div>
{% if doc.documentversion_set.all %}
<table class="table table-bordered"  width="100%" cellspacing="0">
    <thead>
        <tr>
            <th><h3>Version &nbsp; &nbsp; &nbsp; &nbsp;</h3></th>
            <th><h3>Added Version File</h3></th>
            <th><h3>Download</h3></th>
        </tr>
    <tbody>
        <tr>
            {% for version in doc.documentversion_set.all %}
            <tr>
            <td>{{ version.version }}</td>
            <td><a href="{% url 'document:serve_document' version.id %}" style="color: black; text-decoration: none;">{{ version.file.name }}</a></td>
            <td><a href="{% url 'document:download_file'  version.file.path %}"><i class="fas fa-file-download"></i></a></td></tr>
            {% endfor %}
        </tr>
    </tbody>
</table>
{% endif %}
</div>
{% endblock content %}

templates/document/home.html
{% extends 'document/dashboard.html' %}
{% block title %} Document {% endblock%}
{% block content %}
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalCenter" style = "position:relative; left:900px;">Add Document</button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Add New Document</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{% url 'document:home' %}"> 
                    {% csrf_token %}
                    Name &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp; : <input type="text" name="name" style="border-radius: 5px; width: 70%;" required/><br><br>
                    Description &nbsp; &nbsp;:<textarea type="text" name="description" style="border-radius: 5px;width: 70%;" required></textarea><br><br>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-secondary">Save</button>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>            
<!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Document</h1>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-secondary">Document Details</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    {%if document %}
                    <table class="table table-bordered"  width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Created Timestemp</th>
                                <th>View</th>
                                <th>Edit</th>
                                <th>Share</th>
                                <th>Delete</th>
                            </tr>
                        <tbody>
                            <tr>
                                {% for d in document %}
                                <tr>
                                    <td>{{ d.name }}</td>
                                    <td><div class="truncate-text">{{ d.description}}</div></td>
                                    <td>{{ d.created_date }}</td>
                                    <td><a href="{% url 'document:document_version' d.id %}"><i class="fas fa-solid fa-eye" ></i></a></td>
                                    <td><a href="{% url 'document:update_doc' d.id %}" ><i class="fas fa-edit"></i></a></td>
                                    <td><a href="{% url 'document:share' d.id %}" ><i class= "fas fa-share-square"></i></a></td>
                                    <!-- <td><a href="{% url 'document:delete_document' d.id %}" ><i class= "fas fa-share-square"></i></a></td> -->
                                    <td><a data-toggle="modal" data-target="#deleteDocument{{d.id}}"><i class="fas fa-trash-alt"></i></a></td>
                                </tr>
                                <div class="modal fade" id="deleteDocument{{d.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteDocument{{d.id}}Title">Delete document</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <a>Are you sure you want to delete the document "{{ d.name }}"?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <form method="POST" action="{% url 'document:delete_document' d.id%}">
                                                {% csrf_token %}
                                                <input type="submit" value="Delete" class="btn btn-secondary">
                                            </form>
                                        </div>
                                    </div>
                                    </div>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
{% endblock content %}

templates/document/receive.html
{% extends 'document/dashboard.html' %}
{% block title %} Received Document {% endblock%}
{% block content %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Received Document </h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-secondary">Document Details</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                {%if shared_document %}
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Sender Name </th>
                            <th>View</th>
                            <th>Edit</th>
                            <th>Download</th>
                        </tr>
                    <tbody>
                        {% for s in shared_document %}
                        <tr>
                        <td>{{ s.document.name }}</td>
                        <td><div class="truncate-text">{{ s.document.description}}</div></td>
                        <td>{{ s.receiver }}</td>
                        <form method="POST" action="{% url 'document:permission' s.document.id %}">
                            {% csrf_token %}
                            {% if s.shared_doc_view %}
                                <td><button type="submit" name="action" value="view" class="permission_btn"><i class="fas fa-eye"></i>  </button></td> 
                            {% else %}
                                <td> <i class="fas fa-window-close" style="color:red"> </td>
                            {% endif %}

                            {% if s.shared_doc_update %}
                                <td><button type="submit" name="action" value="update" class="permission_btn" ><i class="fas fa-edit"></i></button></td>   
                            {% else %}
                                <td> <i class="fas fa-window-close" style="color:red"> </td>
                            {% endif %}
                            
                            {% if s.shared_doc_download %}
                                <td><button type="submit" name="action" value="download" class="permission_btn"><i class="fas fa-file-download"></i></button></td> 
                            {% else %}
                                <td> <i class="fas fa-window-close" style="color:red"> </td>
                            {% endif %}
                        </form>
                        </tr>    
                    {% endfor %} 
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
{% endblock content %}
         

templates/document/share.html
{% extends 'document/dashboard.html' %}
{% block title %} Shared Document {% endblock%}
{% block content %}
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Document</h1>
    </div>
 <!-- Basic Card Example -->
 <div class="row">
 <div class="col-lg-6">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-secondary">Share Your Document</h6>
        </div>
        <div class="card-body">
            <!-- === -->
            <form method="POST">
                {% csrf_token %}
                    <div class="demo">
                        <label>Share With &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</label><select name='shared_user'> 
                            {% for i in users%}
                            <option value="{{i.id}}"> {{i.username}} </option>    
                            {% endfor %}    
                        </select><br><br>
                    </div>
                    <label>Give Permission  :</label><br>
                        <input type="checkbox" name="shared_doc_view" value="shared_doc_view"> view  <br>
                        <input type="checkbox" name="shared_doc_download" value="shared_doc_download"> download <br>
                        <input type="checkbox" name="shared_doc_update" value="shared_doc_update"> update <br>
                    <input type="submit"> 
            </form>
        </div>
    </div>
</div>
</div>

</div>
{% endblock content %}

templates/document/view.html
{% extends 'document/dashboard.html' %}
{% block title %} View Document {% endblock%}
{% block content %}
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Document</h1>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h5 class="m-0 font-weight-bold text-secondary"> {{ doc.name }} </h5>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample">
                    <div class="card-body truncate-text">
                        {{ doc.description }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
                    role="button" aria-expanded="true" aria-controls="collapseCardExample">
                    <h5 class="m-0 font-weight-bold text-secondary">Version File </h5>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="collapseCardExample">
                    <div class="card-body">
                        <table class="table table-bordered"  width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                {% if versions %}
                                    <th>Version</th>
                                    <th>File</th>
                                </tr> 
                            <tbody>
                                <tr>
                                        {% for version in versions %}
                                        <tr>
                                        <td>{{ version.version }}</td>
                                        <td><a href="{% url 'document:serve_document' version.id %}">{{ version.file.name }}</a></td>
                                    </tr>
                                        {% endfor %}
                                    {% else %}
                                        <td><p>Files are not available.</p></td>
                                    {% endif %}
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
{% endblock content %}
      